### ISSUE TITLE
Error: argument -i/--interval: conflicting option strings: -i, --interval

### ISSUE THREAD

**Issue by juliazero** [maurerle/podman-compose#1]
After installing your podman-compose
```
# curl -o /usr/local/bin/podman-compose https://raw.githubusercontent.com/maurerle/podman-compose/devel/podman_compose.py && chmod +x /usr/local/bin/podman-compose`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  118k  100  118k    0     0   242k      0 --:--:-- --:--:-- --:--:--  242k
```
I received:
```
# podman-compose
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 3486, in <module>
    main()
  File "/usr/local/bin/podman-compose", line 3482, in main
    podman_compose.run()
  File "/usr/local/bin/podman-compose", line 1541, in run
    args = self._parse_args(argv)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/podman-compose", line 1862, in _parse_args
    cmd_parser(subparser)
  File "/usr/local/bin/podman-compose", line 2003, in wrapped
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/podman-compose", line 3457, in compose_stats_parse
    parser.add_argument(
  File "/usr/lib/python3.11/argparse.py", line 1468, in add_argument
    return self._add_action(action)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1850, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python3.11/argparse.py", line 1670, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1482, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.11/argparse.py", line 1619, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.11/argparse.py", line 1628, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--interval: conflicting option strings: -i, --interval

```
I looked if there are duplicated sections, and I found this:
https://github.com/maurerle/podman-compose/blob/b9288f4db3dbb7c7a0e083492cc476f40be5d3a1/podman_compose.py#L3452-L3478 

And this:
https://github.com/maurerle/podman-compose/blob/b9288f4db3dbb7c7a0e083492cc476f40be5d3a1/podman_compose.py#L2928-L2956

Then I removed them and:
```
# podman-compose
usage: podman-compose [-h] [-v] [--no-pod]...
```
It's working now.

**Comment by SebTM** [comment]
Yes commit fd9b446cf8a496d4bd75dc53d90ee4478982bd92 is a duplicate of cb9cf6002ff8691249384786b58e7c0357e4512c ✌🏻 (that's how the code got in double)
